"""Updated category table

Revision ID: 025585af0f82
Revises: 072a530d2679
Create Date: 2026-07-23 14:41:26.853504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025585af0f82'
down_revision: Union[str, Sequence[str], None] = '072a530d2679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('code', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'categories', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'code')
    # ### end Alembic commands ###
