"""create_asset_tables

Revision ID: 59c8ab3299e7
Revises: 046d43cc5528
Create Date: 2026-08-10 23:18:18.429862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c8ab3299e7'
down_revision: Union[str, Sequence[str], None] = '046d43cc5528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('asset_no', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(length=100), nullable=True),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IN_STORE', 'ISSUED', 'UNDER_REPAIR', 'DAMAGED', 'CONDEMNED', 'E_WASTE', 'DISPOSED', name='assetstatus'), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_no'), 'assets', ['asset_no'], unique=True)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_item_id'), 'assets', ['item_id'], unique=False)
    op.create_index(op.f('ix_assets_office_id'), 'assets', ['office_id'], unique=False)
    op.create_index(op.f('ix_assets_section_id'), 'assets', ['section_id'], unique=False)
    op.create_index(op.f('ix_assets_serial_no'), 'assets', ['serial_no'], unique=True)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('asset_details',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_reference', sa.String(length=100), nullable=True),
    sa.Column('purchase_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('warranty_expiry_date', sa.Date(), nullable=True),
    sa.Column('technical_specifications', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_details_asset_id'), 'asset_details', ['asset_id'], unique=True)
    op.create_index(op.f('ix_asset_details_id'), 'asset_details', ['id'], unique=False)
    op.create_table('asset_movements',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('RECEIPT', 'ISSUE', 'TRANSFER', 'RETURN', name='assetmovementtype'), nullable=False),
    sa.Column('from_office_id', sa.Integer(), nullable=True),
    sa.Column('from_section_id', sa.Integer(), nullable=True),
    sa.Column('to_office_id', sa.Integer(), nullable=True),
    sa.Column('to_section_id', sa.Integer(), nullable=True),
    sa.Column('reference_document', sa.String(length=100), nullable=True),
    sa.Column('movement_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['from_office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['from_section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['to_office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['to_section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_movements_asset_id'), 'asset_movements', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_movements_from_office_id'), 'asset_movements', ['from_office_id'], unique=False)
    op.create_index(op.f('ix_asset_movements_from_section_id'), 'asset_movements', ['from_section_id'], unique=False)
    op.create_index(op.f('ix_asset_movements_id'), 'asset_movements', ['id'], unique=False)
    op.create_index(op.f('ix_asset_movements_to_office_id'), 'asset_movements', ['to_office_id'], unique=False)
    op.create_index(op.f('ix_asset_movements_to_section_id'), 'asset_movements', ['to_section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_movements_to_section_id'), table_name='asset_movements')
    op.drop_index(op.f('ix_asset_movements_to_office_id'), table_name='asset_movements')
    op.drop_index(op.f('ix_asset_movements_id'), table_name='asset_movements')
    op.drop_index(op.f('ix_asset_movements_from_section_id'), table_name='asset_movements')
    op.drop_index(op.f('ix_asset_movements_from_office_id'), table_name='asset_movements')
    op.drop_index(op.f('ix_asset_movements_asset_id'), table_name='asset_movements')
    op.drop_table('asset_movements')
    op.drop_index(op.f('ix_asset_details_id'), table_name='asset_details')
    op.drop_index(op.f('ix_asset_details_asset_id'), table_name='asset_details')
    op.drop_table('asset_details')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_serial_no'), table_name='assets')
    op.drop_index(op.f('ix_assets_section_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_office_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_item_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_no'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
