"""create_transaction_and_stock_ledger_tables

Revision ID: 7ba67cd08ee5
Revises: 7fb3f165910d
Create Date: 2026-08-11 12:38:39.551386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba67cd08ee5'
down_revision: Union[str, Sequence[str], None] = '7fb3f165910d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_movements',
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.Enum('OPENING', 'RECEIPT', 'ISSUE', 'RETURN', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', name='movementtype'), nullable=False),
    sa.Column('transaction_source', sa.Enum('OPENING', 'HISTORICAL', 'OPERATIONAL', name='transactionsource'), nullable=False),
    sa.Column('quantity_in', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_out', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('movement_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_financial_year_id'), 'stock_movements', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_id'), 'stock_movements', ['id'], unique=False)
    op.create_index(op.f('ix_stock_movements_item_id'), 'stock_movements', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_movement_type'), 'stock_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_stock_movements_office_id'), 'stock_movements', ['office_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_reference_id'), 'stock_movements', ['reference_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_reference_type'), 'stock_movements', ['reference_type'], unique=False)
    op.create_index(op.f('ix_stock_movements_section_id'), 'stock_movements', ['section_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_transaction_source'), 'stock_movements', ['transaction_source'], unique=False)
    op.create_table('receipts',
    sa.Column('receipt_no', sa.String(length=50), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('supplier_name', sa.String(length=150), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_financial_year_id'), 'receipts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_receipts_id'), 'receipts', ['id'], unique=False)
    op.create_index(op.f('ix_receipts_office_id'), 'receipts', ['office_id'], unique=False)
    op.create_index(op.f('ix_receipts_receipt_no'), 'receipts', ['receipt_no'], unique=True)
    op.create_index(op.f('ix_receipts_section_id'), 'receipts', ['section_id'], unique=False)
    op.create_index(op.f('ix_receipts_status'), 'receipts', ['status'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('transfer_no', sa.String(length=50), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('from_office_id', sa.Integer(), nullable=False),
    sa.Column('from_section_id', sa.Integer(), nullable=True),
    sa.Column('to_office_id', sa.Integer(), nullable=False),
    sa.Column('to_section_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.ForeignKeyConstraint(['from_office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['from_section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['to_section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfers_financial_year_id'), 'stock_transfers', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_from_office_id'), 'stock_transfers', ['from_office_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_from_section_id'), 'stock_transfers', ['from_section_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_id'), 'stock_transfers', ['id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_status'), 'stock_transfers', ['status'], unique=False)
    op.create_index(op.f('ix_stock_transfers_to_office_id'), 'stock_transfers', ['to_office_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_to_section_id'), 'stock_transfers', ['to_section_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_transfer_no'), 'stock_transfers', ['transfer_no'], unique=True)
    op.create_table('issues',
    sa.Column('issue_no', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('indent_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('destination_type', sa.Enum('INTERNAL', 'EXTERNAL', name='destinationtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.ForeignKeyConstraint(['indent_id'], ['indents.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_financial_year_id'), 'issues', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)
    op.create_index(op.f('ix_issues_indent_id'), 'issues', ['indent_id'], unique=False)
    op.create_index(op.f('ix_issues_issue_no'), 'issues', ['issue_no'], unique=True)
    op.create_index(op.f('ix_issues_office_id'), 'issues', ['office_id'], unique=False)
    op.create_index(op.f('ix_issues_section_id'), 'issues', ['section_id'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    op.create_table('receipt_lines',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_lines_id'), 'receipt_lines', ['id'], unique=False)
    op.create_index(op.f('ix_receipt_lines_item_id'), 'receipt_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_receipt_lines_receipt_id'), 'receipt_lines', ['receipt_id'], unique=False)
    op.create_table('stock_transfer_lines',
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfer_lines_id'), 'stock_transfer_lines', ['id'], unique=False)
    op.create_index(op.f('ix_stock_transfer_lines_item_id'), 'stock_transfer_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_transfer_lines_transfer_id'), 'stock_transfer_lines', ['transfer_id'], unique=False)
    op.create_table('issue_lines',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_lines_id'), 'issue_lines', ['id'], unique=False)
    op.create_index(op.f('ix_issue_lines_issue_id'), 'issue_lines', ['issue_id'], unique=False)
    op.create_index(op.f('ix_issue_lines_item_id'), 'issue_lines', ['item_id'], unique=False)
    op.create_table('outward_passes',
    sa.Column('pass_no', sa.String(length=50), nullable=False),
    sa.Column('pass_date', sa.Date(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('vehicle_no', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outward_passes_id'), 'outward_passes', ['id'], unique=False)
    op.create_index(op.f('ix_outward_passes_issue_id'), 'outward_passes', ['issue_id'], unique=True)
    op.create_index(op.f('ix_outward_passes_pass_no'), 'outward_passes', ['pass_no'], unique=True)
    op.create_table('stock_returns',
    sa.Column('return_no', sa.String(length=50), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('reference_issue_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reference_issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_returns_financial_year_id'), 'stock_returns', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_stock_returns_id'), 'stock_returns', ['id'], unique=False)
    op.create_index(op.f('ix_stock_returns_office_id'), 'stock_returns', ['office_id'], unique=False)
    op.create_index(op.f('ix_stock_returns_reference_issue_id'), 'stock_returns', ['reference_issue_id'], unique=False)
    op.create_index(op.f('ix_stock_returns_return_no'), 'stock_returns', ['return_no'], unique=True)
    op.create_index(op.f('ix_stock_returns_section_id'), 'stock_returns', ['section_id'], unique=False)
    op.create_index(op.f('ix_stock_returns_status'), 'stock_returns', ['status'], unique=False)
    op.create_table('stock_transfer_line_assets',
    sa.Column('transfer_line_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['transfer_line_id'], ['stock_transfer_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfer_line_assets_asset_id'), 'stock_transfer_line_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_stock_transfer_line_assets_id'), 'stock_transfer_line_assets', ['id'], unique=False)
    op.create_index(op.f('ix_stock_transfer_line_assets_transfer_line_id'), 'stock_transfer_line_assets', ['transfer_line_id'], unique=False)
    op.create_table('issue_line_assets',
    sa.Column('issue_line_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['issue_line_id'], ['issue_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_line_assets_asset_id'), 'issue_line_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_issue_line_assets_id'), 'issue_line_assets', ['id'], unique=False)
    op.create_index(op.f('ix_issue_line_assets_issue_line_id'), 'issue_line_assets', ['issue_line_id'], unique=False)
    op.create_table('stock_return_lines',
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['stock_returns.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_return_lines_id'), 'stock_return_lines', ['id'], unique=False)
    op.create_index(op.f('ix_stock_return_lines_item_id'), 'stock_return_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_return_lines_return_id'), 'stock_return_lines', ['return_id'], unique=False)
    op.create_table('stock_return_line_assets',
    sa.Column('return_line_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['return_line_id'], ['stock_return_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_return_line_assets_asset_id'), 'stock_return_line_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_stock_return_line_assets_id'), 'stock_return_line_assets', ['id'], unique=False)
    op.create_index(op.f('ix_stock_return_line_assets_return_line_id'), 'stock_return_line_assets', ['return_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_return_line_assets_return_line_id'), table_name='stock_return_line_assets')
    op.drop_index(op.f('ix_stock_return_line_assets_id'), table_name='stock_return_line_assets')
    op.drop_index(op.f('ix_stock_return_line_assets_asset_id'), table_name='stock_return_line_assets')
    op.drop_table('stock_return_line_assets')
    op.drop_index(op.f('ix_stock_return_lines_return_id'), table_name='stock_return_lines')
    op.drop_index(op.f('ix_stock_return_lines_item_id'), table_name='stock_return_lines')
    op.drop_index(op.f('ix_stock_return_lines_id'), table_name='stock_return_lines')
    op.drop_table('stock_return_lines')
    op.drop_index(op.f('ix_issue_line_assets_issue_line_id'), table_name='issue_line_assets')
    op.drop_index(op.f('ix_issue_line_assets_id'), table_name='issue_line_assets')
    op.drop_index(op.f('ix_issue_line_assets_asset_id'), table_name='issue_line_assets')
    op.drop_table('issue_line_assets')
    op.drop_index(op.f('ix_stock_transfer_line_assets_transfer_line_id'), table_name='stock_transfer_line_assets')
    op.drop_index(op.f('ix_stock_transfer_line_assets_id'), table_name='stock_transfer_line_assets')
    op.drop_index(op.f('ix_stock_transfer_line_assets_asset_id'), table_name='stock_transfer_line_assets')
    op.drop_table('stock_transfer_line_assets')
    op.drop_index(op.f('ix_stock_returns_status'), table_name='stock_returns')
    op.drop_index(op.f('ix_stock_returns_section_id'), table_name='stock_returns')
    op.drop_index(op.f('ix_stock_returns_return_no'), table_name='stock_returns')
    op.drop_index(op.f('ix_stock_returns_reference_issue_id'), table_name='stock_returns')
    op.drop_index(op.f('ix_stock_returns_office_id'), table_name='stock_returns')
    op.drop_index(op.f('ix_stock_returns_id'), table_name='stock_returns')
    op.drop_index(op.f('ix_stock_returns_financial_year_id'), table_name='stock_returns')
    op.drop_table('stock_returns')
    op.drop_index(op.f('ix_outward_passes_pass_no'), table_name='outward_passes')
    op.drop_index(op.f('ix_outward_passes_issue_id'), table_name='outward_passes')
    op.drop_index(op.f('ix_outward_passes_id'), table_name='outward_passes')
    op.drop_table('outward_passes')
    op.drop_index(op.f('ix_issue_lines_item_id'), table_name='issue_lines')
    op.drop_index(op.f('ix_issue_lines_issue_id'), table_name='issue_lines')
    op.drop_index(op.f('ix_issue_lines_id'), table_name='issue_lines')
    op.drop_table('issue_lines')
    op.drop_index(op.f('ix_stock_transfer_lines_transfer_id'), table_name='stock_transfer_lines')
    op.drop_index(op.f('ix_stock_transfer_lines_item_id'), table_name='stock_transfer_lines')
    op.drop_index(op.f('ix_stock_transfer_lines_id'), table_name='stock_transfer_lines')
    op.drop_table('stock_transfer_lines')
    op.drop_index(op.f('ix_receipt_lines_receipt_id'), table_name='receipt_lines')
    op.drop_index(op.f('ix_receipt_lines_item_id'), table_name='receipt_lines')
    op.drop_index(op.f('ix_receipt_lines_id'), table_name='receipt_lines')
    op.drop_table('receipt_lines')
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_section_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_office_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_issue_no'), table_name='issues')
    op.drop_index(op.f('ix_issues_indent_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_financial_year_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_stock_transfers_transfer_no'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_to_section_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_to_office_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_status'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_from_section_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_from_office_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_financial_year_id'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_index(op.f('ix_receipts_status'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_section_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_receipt_no'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_office_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_financial_year_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_stock_movements_transaction_source'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_section_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_reference_type'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_reference_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_office_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_movement_type'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_item_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_financial_year_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    # ### end Alembic commands ###
