"""create_indent_tables

Revision ID: 7fb3f165910d
Revises: 59c8ab3299e7
Create Date: 2026-08-10 23:45:32.178228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb3f165910d'
down_revision: Union[str, Sequence[str], None] = '59c8ab3299e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indents',
    sa.Column('indent_no', sa.String(length=50), nullable=False),
    sa.Column('indent_date', sa.Date(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('request_source', sa.Enum('PHYSICAL', 'ONLINE', name='requestsource'), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'CLOSED', 'SUBMITTED', 'OFFICE_APPROVED', 'HEAD_OFFICE_APPROVED', 'SENT_TO_STORE', 'REJECTED', name='indentstatus'), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('processed_by_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_year_id', 'office_id', 'indent_no', name='uq_indent_fy_office_no')
    )
    op.create_index(op.f('ix_indents_financial_year_id'), 'indents', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_indents_id'), 'indents', ['id'], unique=False)
    op.create_index(op.f('ix_indents_indent_no'), 'indents', ['indent_no'], unique=False)
    op.create_index(op.f('ix_indents_office_id'), 'indents', ['office_id'], unique=False)
    op.create_index(op.f('ix_indents_section_id'), 'indents', ['section_id'], unique=False)
    op.create_index(op.f('ix_indents_status'), 'indents', ['status'], unique=False)
    op.create_table('indent_lines',
    sa.Column('indent_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('issued_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['indent_id'], ['indents.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indent_id', 'item_id', name='uq_indent_line_item')
    )
    op.create_index(op.f('ix_indent_lines_id'), 'indent_lines', ['id'], unique=False)
    op.create_index(op.f('ix_indent_lines_indent_id'), 'indent_lines', ['indent_id'], unique=False)
    op.create_index(op.f('ix_indent_lines_item_id'), 'indent_lines', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indent_lines_item_id'), table_name='indent_lines')
    op.drop_index(op.f('ix_indent_lines_indent_id'), table_name='indent_lines')
    op.drop_index(op.f('ix_indent_lines_id'), table_name='indent_lines')
    op.drop_table('indent_lines')
    op.drop_index(op.f('ix_indents_status'), table_name='indents')
    op.drop_index(op.f('ix_indents_section_id'), table_name='indents')
    op.drop_index(op.f('ix_indents_office_id'), table_name='indents')
    op.drop_index(op.f('ix_indents_indent_no'), table_name='indents')
    op.drop_index(op.f('ix_indents_id'), table_name='indents')
    op.drop_index(op.f('ix_indents_financial_year_id'), table_name='indents')
    op.drop_table('indents')
    # ### end Alembic commands ###
