"""Add unique constraints to units

Revision ID: 8650773ab9d0
Revises: e593e52cf17e
Create Date: 2026-07-21 22:09:56.259287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8650773ab9d0'
down_revision: Union[str, Sequence[str], None] = 'e593e52cf17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_units_name'), 'units', ['name'], unique=True)
    op.create_unique_constraint(None, 'units', ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units', type_='unique')
    op.drop_index(op.f('ix_units_name'), table_name='units')
    # ### end Alembic commands ###
