"""create office master table

Revision ID: e593e52cf17e
Revises: 791c932eab51
Create Date: 2026-07-20 10:02:11.343337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e593e52cf17e'
down_revision: Union[str, Sequence[str], None] = '791c932eab51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('office_type', sa.Enum('DIRECTORATE', 'GCP', 'BRANCH', 'DISTRICT_FORM_STORE', name='officetype'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offices_code'), 'offices', ['code'], unique=True)
    op.create_index(op.f('ix_offices_id'), 'offices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offices_id'), table_name='offices')
    op.drop_index(op.f('ix_offices_code'), table_name='offices')
    op.drop_table('offices')
    # ### end Alembic commands ###
